// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Szakmak.Data;

#nullable disable

namespace Szakmak.Migrations
{
    [DbContext(typeof(SzakmakDbContext))]
    partial class SzakmakDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Szakmak.Models.Orszag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrszagNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orszagok");
                });

            modelBuilder.Entity("Szakmak.Models.Szakma", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SzakmaNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Szakmak");
                });

            modelBuilder.Entity("Szakmak.Models.Versenyzo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrszagId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pont")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SzakmaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrszagId");

                    b.HasIndex("SzakmaId");

                    b.ToTable("Versenyzok");
                });

            modelBuilder.Entity("Szakmak.Models.Versenyzo", b =>
                {
                    b.HasOne("Szakmak.Models.Orszag", "Orszag")
                        .WithMany("Versenyzok")
                        .HasForeignKey("OrszagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Szakmak.Models.Szakma", "Szakma")
                        .WithMany("Versenyzok")
                        .HasForeignKey("SzakmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orszag");

                    b.Navigation("Szakma");
                });

            modelBuilder.Entity("Szakmak.Models.Orszag", b =>
                {
                    b.Navigation("Versenyzok");
                });

            modelBuilder.Entity("Szakmak.Models.Szakma", b =>
                {
                    b.Navigation("Versenyzok");
                });
#pragma warning restore 612, 618
        }
    }
}
